# Generated by Django 4.1.7 on 2023-03-31 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='offset',
            fields=[
                ('store_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('loc', models.TextField()),
                ('name', models.TextField()),
                ('abbrevation', models.TextField()),
                ('offset', models.DurationField()),
                ('is_dst', models.BooleanField()),
            ],
            options={
                'db_table': 'id_offset',
            },
        ),
    ]
